colorscheme desert
set guifont=Anonymous\ Pro\ 12
set nocompatible
filetype off
let mapleader = "."

"#Local dirs
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
set undodir=~/.vim/undo

"#Window size
"set lines=57					" This changes size of terminal windows 
set columns=117

"#Settings
"set autoindent					" Copy indent from last line when starting new line.
set backspace=indent,eol,start	" Backspace behavior
set cursorline 					" Highlight current line
set diffopt+=iwhite 			" Ignore whitespace changes (focus on code changes)
set encoding=utf-8 nobomb 		" BOM often causes trouble
set esckeys 					" Allow cursor keys in insert mode.
"set expandtab 					" Always uses spaces instead of tab characters
set history=1000 				" Increase history from 20 default to 1000
set hlsearch 					" Highlight searches
set ignorecase 					" Ignore case of searches.
set incsearch 					" Highlight dynamically as pattern is typed.
set laststatus=2 				" Always show status line
set magic 						" Enable extended regexes.
set noerrorbells 				" Disable error bells.
set nu	 						" Enable line numbers.
set ruler 						" Show the cursor position
set scrolloff=3 				" Start scrolling three lines before horizontal border of window.
"set shiftwidth=4 				" The # of spaces for indenting. Use with extendtab.
set shortmess=atI 				" Don't show the intro message when starting vim.
set showmode 					" Show the current mode.
set sidescrolloff=3 			" Start scrolling three columns before vertical border of window.
set smartcase 					" Ignore 'ignorecase' if search patter contains uppercase characters.
set tabstop=4 					" size of a hard tabstop
set title 						" Show the filename in the window titlebar.
set ttyfast 					" Send more characters at a given time.
set undofile 					" Persistent Undo.
set visualbell 					" Use visual bell instead of audible bell (annnnnoying)
set wildchar=<TAB> 				" Character for CLI expansion (TAB-completion).

"#Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"#core Vundle
Plugin 'gmarik/Vundle.vim'
"#vim-task
Plugin 'thrstn/vim-task'
"#emmet
Plugin 'mattn/emmet-vim.git'
"#airline
Plugin 'bling/vim-airline.git'

call vundle#end()
"filetype plugin indent on


"#vim-task
:map <Leader>T :setfiletype task<CR>
:map <Leader>. :call Toggle_task_status()<CR>


"#emmet
let g:user_emmet_leader_key='<C-E>' " remap leader


"#airline
let g:airline_powerline_fonts = 1


"#Remaps
"command W w
"command Wq wq
"command Q q

"#Methods

"#Strip trailing whitespace (,ss)
function! StripWhitespace ()
	let save_cursor = getpos(".")
	let old_query = getreg('/')
	:%s/\s\+$//e
	call setpos('.', save_cursor)
	call setreg('/', old_query)
endfunction
noremap <leader>ss :call StripWhitespace ()<CR>
